### ISSUE TITLE
A stemmer for Ukrainian

### ISSUE THREAD

**Issue by egorsmkv** [tebeka/snowball#1]
Hello.

Is it possible to add a stemmer for the Ukrainian language?

UPD: I've found this: https://github.com/Tapkomet/UAStemming

**Comment by tebeka** [comment]
This is a thin wrapper around [snowball stemmer](http://snowball.tartarus.org/) which IMO does support  Ukrainian. If a new version comes up with support, I'll gladly update this packge.

**Comment by egorsmkv** [comment]
If so it would be great :)

**Comment by egorsmkv** [comment]
Unfortunately, I don't see any progress on this issue.

BTW, https://github.com/snowballstem/snowball/issues/130

**Comment by tebeka** [comment]
The above issue in snowball is still open. Once they implement Ukrainian I'll gladly update the package.

**Comment by tebeka** [comment]
Done in v0.6.0 (updated snowball to 2.2.0)
