### ISSUE TITLE
List of available languages

### ISSUE THREAD

**Issue by hugolgst** [tebeka/snowball#4]
You should add a list of available languages for your stemmer

**Comment by tebeka** [comment]
As in [LangList](https://godoc.org/github.com/tebeka/snowball#LangList)?

**Comment by hugolgst** [comment]
Exactly but in the README.md, sorry I didn't specify that

**Comment by tebeka** [comment]
Fixed in 731032d38b3af8bb0cdb9fb44b6dec169c1cba70, thanks.
